//guh
export const RAW_CODE_TO_KEY_NAME = {
    27: "key_escape",
    49: "key_1",
    50: "key_2",
    51: "key_3",
    52: "key_4",
    53: "key_5",
    54: "key_6",
    55: "key_7",
    56: "key_8",
    57: "key_9",
    48: "key_0",
    189: "key_minus",
    187: "key_equals",
    8: "key_backspace",
    112: "key_f1",
    113: "key_f2",
    114: "key_f3",
    115: "key_f4",
    116: "key_f5",
    117: "key_f6",
    118: "key_f7",
    119: "key_f8",
    120: "key_f9",
    121: "key_f10",
    122: "key_f11",
    123: "key_f12",
    44: "key_printscreen",
    145: "key_scrolllock",
    19: "key_pause",
    45: "key_insert",
    46: "key_delete",
    36: "key_home",
    35: "key_end",
    33: "key_pageup",
    34: "key_pagedown",
    9: "key_tab",
    81: "key_q",
    87: "key_w",
    69: "key_e",
    82: "key_r",
    84: "key_t",
    89: "key_y",
    85: "key_u",
    73: "key_i",
    79: "key_o",
    80: "key_p",
    219: "key_openbracket",
    221: "key_closebracket",
    220: "key_backslash",
    20: "key_capslock",
    65: "key_a",
    83: "key_s",
    68: "key_d",
    70: "key_f",
    71: "key_g",
    72: "key_h",
    74: "key_j",
    75: "key_k",
    76: "key_l",
    186: "key_semicolon",
    222: "key_apostrophe",
    13: "key_enter",
    160: "key_leftshift",
    90: "key_z",
    88: "key_x",
    67: "key_c",
    86: "key_v",
    66: "key_b",
    78: "key_n",
    77: "key_m",
    188: "key_comma",
    190: "key_period",
    191: "key_slash",
    161: "key_rightshift",
    162: "key_leftctrl",
    91: "key_leftwin",
    164: "key_leftalt",
    32: "key_space",
    165: "key_rightalt",
    92: "key_rightwin",
    93: "key_menu",
    163: "key_rightctrl",
    37: "key_leftarrow",
    38: "key_uparrow",
    39: "key_rightarrow",
    40: "key_downarrow",
    144: "key_numlock",
    111: "key_numpad_divide",
    106: "key_numpad_multiply",
    109: "key_numpad_subtract",
    103: "key_numpad_7",
    104: "key_numpad_8",
    105: "key_numpad_9",
    107: "key_numpad_add",
    100: "key_numpad_4",
    101: "key_numpad_5",
    102: "key_numpad_6",
    97: "key_numpad_1",
    98: "key_numpad_2",
    99: "key_numpad_3",
    108: "key_numpad_enter",
    96: "key_numpad_0",
    110: "key_numpad_decimal"
};

export const BROWSER_CODE_TO_KEY_NAME = {
    "escape": "key_escape",
    "digit1": "key_1",
    "digit2": "key_2",
    "digit3": "key_3",
    "digit4": "key_4",
    "digit5": "key_5",
    "digit6": "key_6",
    "digit7": "key_7",
    "digit8": "key_8",
    "digit9": "key_9",
    "digit0": "key_0",
    "minus": "key_minus",
    "equal": "key_equals",
    "backspace": "key_backspace",
    "f1": "key_f1",
    "f2": "key_f2",
    "f3": "key_f3",
    "f4": "key_f4",
    "f5": "key_f5",
    "f6": "key_f6",
    "f7": "key_f7",
    "f8": "key_f8",
    "f9": "key_f9",
    "f10": "key_f10",
    "f11": "key_f11",
    "f12": "key_f12",
    "printscreen": "key_printscreen",
    "scrolllock": "key_scrolllock",
    "pause": "key_pause",
    "insert": "key_insert",
    "delete": "key_delete",
    "home": "key_home",
    "end": "key_end",
    "pageup": "key_pageup",
    "pagedown": "key_pagedown",
    "tab": "key_tab",
    "keyq": "key_q",
    "keyw": "key_w",
    "keye": "key_e",
    "keyr": "key_r",
    "keyt": "key_t",
    "keyy": "key_y",
    "keyu": "key_u",
    "keyi": "key_i",
    "keyo": "key_o",
    "keyp": "key_p",
    "bracketleft": "key_openbracket",
    "bracketright": "key_closebracket",
    "backslash": "key_backslash",
    "capslock": "key_capslock",
    "keya": "key_a",
    "keys": "key_s",
    "keyd": "key_d",
    "keyf": "key_f",
    "keyg": "key_g",
    "keyh": "key_h",
    "keyj": "key_j",
    "keyk": "key_k",
    "keyl": "key_l",
    "semicolon": "key_semicolon",
    "quote": "key_apostrophe",
    "enter": "key_enter",
    "shiftleft": "key_leftshift",
    "keyz": "key_z",
    "keyx": "key_x",
    "keyc": "key_c",
    "keyv": "key_v",
    "keyb": "key_b",
    "keyn": "key_n",
    "keym": "key_m",
    "comma": "key_comma",
    "period": "key_period",
    "slash": "key_slash",
    "shiftright": "key_rightshift",
    "controlleft": "key_leftctrl",
    "metaleft": "key_leftwin",
    "altleft": "key_leftalt",
    "space": "key_space",
    "altright": "key_rightalt",
    "metaright": "key_rightwin",
    "contextmenu": "key_menu",
    "controlright": "key_rightctrl",
    "arrowleft": "key_leftarrow",
    "arrowup": "key_uparrow",
    "arrowright": "key_rightarrow",
    "arrowdown": "key_downarrow",
    "numlock": "key_numlock",
    "numpaddivide": "key_numpad_divide",
    "numpadmultiply": "key_numpad_multiply",
    "numpadsubtract": "key_numpad_subtract",
    "numpad7": "key_numpad_7",
    "numpad8": "key_numpad_8",
    "numpad9": "key_numpad_9",
    "numpadadd": "key_numpad_add",
    "numpad4": "key_numpad_4",
    "numpad5": "key_numpad_5",
    "numpad6": "key_numpad_6",
    "numpad1": "key_numpad_1",
    "numpad2": "key_numpad_2",
    "numpad3": "key_numpad_3",
    "numpadenter": "key_numpad_enter",
    "numpad0": "key_numpad_0",
    "numpaddecimal": "key_numpad_decimal"
};

export const MOUSE_BUTTON_MAP = {
    1: "mouse_left",
    2: "mouse_right",
    3: "mouse_middle",
    4: "mouse4",
    5: "mouse5"
};

export const BROWSER_BUTTON_TO_KEY_NAME = {
    0: "mouse_left",
    1: "mouse_middle",
    2: "mouse_right",
    3: "mouse4",
    4: "mouse5"
};

export const DEFAULT_LAYOUT_STRINGS = {
    row1: "key_escape:\"invis\", key_1:\"1\", key_2:\"2\", key_3:\"3\", key_4:\"4\"",
    row2: "key_tab:\"TAB\":u1-5, key_q:\"Q\", key_w:\"W\", key_e:\"E\", key_r:\"R\"",
    row3: "key_leftshift:\"SHIFT\":u2, key_a:\"A\", key_s:\"S\", key_d:\"D\", key_f:\"F\"",
    row4: "",
    row5: "key_leftctrl:\"CTRL\":u1-5, key_leftalt:\"ALT\":u1-5, key_space:\"SPACE\":u3-33",
    mouse: "mouse_left:\"M1\":u2-47, scroller:\"M3\":\"🡅\":\"🡇\", mouse_right:\"M2\":u2-47"
};

export const COLOR_PICKERS = [
    {id: "activecolor", defaultColor: "#8b5cf6"},
    {id: "backgroundcolor", defaultColor: "#1a1a1ad1"},
    {id: "activebgcolor", defaultColor: "#202020"},
    {id: "outlinecolor", defaultColor: "#4f4f4f"},
    {id: "fontcolor", defaultColor: "#ffffff"},
    {id: "inactivecolor", defaultColor: "#808080"}
];

export const FONT_FAMILY_LINKS = {
    "abel": "https://fonts.googleapis.com/css2?family=Abel&display=swap",
    "archivo-black": "https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap",
    "arimo": "https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400..700;1,400..700&display=swap",
    "bebas-neue": "https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap",
    "bitcount-prop-single": "https://fonts.googleapis.com/css2?family=Bitcount+Prop+Single:wght@100..900&display=swap",
    "bungee": "https://fonts.googleapis.com/css2?family=Bungee&display=swap",
    "caveat-brush": "https://fonts.googleapis.com/css2?family=Caveat+Brush&display=swap",
    "chewy": "https://fonts.googleapis.com/css2?family=Chewy&display=swap",
    "cinzel": "https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&display=swap",
    "comfortaa": "https://fonts.googleapis.com/css2?family=Comfortaa:wght@300..700&display=swap",
    "fjalla-one": "https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap",
    "fredoka": "https://fonts.googleapis.com/css2?family=Fredoka:wght@300..700&display=swap",
    "inter": "https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap",
    "josefin-sans": "https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&display=swap",
    "knewave": "https://fonts.googleapis.com/css2?family=Knewave&display=swap",
    "lato": "https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap",
    "lexend": "https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap",
    "lexend-giga": "https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@100..900&display=swap",
    "lilita-one": "https://fonts.googleapis.com/css2?family=Lilita+One&display=swap",
    "montserrat": "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap",
    "noto-sans": "https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap",
    "open-sans": "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap",
    "orbitron": "https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap",
    "oswald": "https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap",
    "pacifico": "https://fonts.googleapis.com/css2?family=Pacifico&display=swap",
    "press-start-2p": "https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap",
    "raleway": "https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap",
    "roboto-condensed": "https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,100..900;1,100..900&display=swap",
    "roboto-mono": "https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap",
    "roboto": "https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap",
    "share-tech": "https://fonts.googleapis.com/css2?family=Share+Tech&display=swap",
    "smooch-sans": "https://fonts.googleapis.com/css2?family=Smooch+Sans:wght@100..900&display=swap",
    "sora": "https://fonts.googleapis.com/css2?family=Sora:wght@100..800&display=swap",
    "special-elite": "https://fonts.googleapis.com/css2?family=Special+Elite&display=swap",
    "titan-one": "https://fonts.googleapis.com/css2?family=Titan+One&display=swap",
    "ubuntu": "https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
};