name: puh ges

on:
  push:
    branches:
      - main
    paths:
      - "overlay/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: add CNAME
        run: cp CNAME overlay/CNAME

      - name: setup pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: overlay

      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
